import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.ClimateScienceNorthAtlanticOscillationTheoremCanonicalLaneLean.NAODynamics
import HautevilleHouse.ClimateScienceNorthAtlanticOscillationTheoremCanonicalLaneLean.IsotopicPaleothermometry
import HautevilleHouse.ClimateScienceNorthAtlanticOscillationTheoremCanonicalLaneLean.MilankovitchCycles
import HautevilleHouse.ClimateScienceNorthAtlanticOscillationTheoremCanonicalLaneLean.DansgaardOeschgerEvents
import HautevilleHouse.ClimateScienceNorthAtlanticOscillationTheoremCanonicalLaneLean.EnergyBalanceModel
import HautevilleHouse.ClimateScienceNorthAtlanticOscillationTheoremCanonicalLaneLean.NorthAtlanticOscillationIndex

namespace HautevilleHouse
namespace ClimateScienceNorthAtlanticOscillationTheoremCanonicalLaneLean

def ConstrainedNAOClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_nao_endgame (A : AdmissibleClass) :
    ConstrainedNAOClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end ClimateScienceNorthAtlanticOscillationTheoremCanonicalLaneLean
end HautevilleHouse